export const CONST = {
  accessToken: "accessToken",
  currentUser: "currentUser",
  username: "username",
  password: "password",
  defaultIngredientImage: 'assets/default-img.png',
};
export const APP_TITLE = "HealthSphere";
export const UI_TEXTS = {
  APP_TITLE: APP_TITLE,
  SIGN_IN_TITLE: "Sign in to your account",
  SIGN_UP_TITLE: "Sign Up",
  CREATE_ACCOUNT_PROMPT: "Don’t have an account yet?",
  EMAIL_LABEL: "Your Email",
  EMAIL_REQUIRED_ERROR: "Email is required.",
  EMAIL_INVALID_ERROR: "Enter a valid email.",
  PASSWORD_LABEL: "Password",
  PASSWORD_REQUIRED_ERROR: "Password is required.",
  USERNAME_LABEL: "Username",
  USERNAME_REQUIRED_ERROR: "Username is required.",
  NUTRITION: "Nutrition",
  WEIGHT: "Weight",
  ROUTINES: "Routines",
  PREFERENCES: "Preferences",
  LOGIN: "Login",
  LOGOUT: "Logout",
  SUBMIT: "Submit",
  BIRTHDATE: "Birthdate",
  SAVE: "Save",
  PROFILE: "Profile",
  HEIGHT: "Height",
  API_ERROR: "An unexpected error occurred. Please try again later.",
  LOGIN_ERROR: "Invalid credentials. Please try again.",
  USER_SETTINGS_UPDATE_SUCCESS: "User settings updated successfully!",
  INVALID_DATA: "Invalid data provided.",
  UNAUTHORIZED: "Unauthorized. Please log in again."
};
